### ISSUE TITLE
Does not accept float number

### ISSUE THREAD

**Issue by opicarellieldorado** [arnu515/donttrust#4]
If you try to validate float number like 0.25 it will get exception:

1. first try float with default multiple
```Schema("quantity").number().float().min(0).max(1000).required()```
"\"quantity\" should be a multiple of 1"

2. second try with precision multiple
```Schema("quantity").number().float().multiple(0.1).min(0).max(1000).required()```
"\"quantity\" should be a multiple of 0.1"

In the second case the problem is:
```
        if value % self._multiple_of != 0:
            raise MultipleException(self.field, self._multiple_of)
```

if you test 0.25 % 0.1 it will be "0.04999999999999999" that is different of 0

**Comment by arnu515** [comment]
In the code, the `multiple` function only accepts integers as its argument, and that's because floating point maths is weird.

You're not supposed to give a float in the `multiple()` function.

As for the first problem, I'll create a PR for fixing that.

**Comment by arnu515** [comment]
Update: Said PR is at #5
